import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { trpc } from "@/utils/trpc";
import { NotationData } from "@/types";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import Link from "next/link";
import { useSession } from "next-auth/react";
import ComboList from "@/components/ComboList";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import VisuallyHidden from "@/components/VisuallyHidden";

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  const loggedIn = status === "authenticated";

  const { data: characters, isLoading } = trpc.useQuery([
    "character.getAll"
  ]);
  const { data: combos } = trpc.useQuery(["combo.getAll"]);
  if (isLoading || !characters || !combos) return <div>Loading...</div>;

  return (
    <>
      <Header />
      <Layout>
        <Head>
          <title>Dragon Rush</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MaxWidthWrapper>
          <VisuallyHidden as="h1">ComboZ</VisuallyHidden>
          <WelcomeMessage>
            Welcome{' '}
            {loggedIn
              ? `${session?.user?.name}, lets build a combo!`
              : 'to ComboZ'}
          </WelcomeMessage>
          <p>Build and share combos!</p>
          <ComboList />
        </MaxWidthWrapper>
      </Layout>
      <Footer />
    </>
  );
};

const Wrapper = styled.div``;

const WelcomeMessage = styled.h2`
  font-size: ${32 / 16}rem;
`;

const CharacterName = styled.div`
  color: red;
`;

export default Home;
